spring:
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_221229?characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  main:
    allow-circular-references: true    
  mail:
    host: smtp.gmail.com
    port: 465
    username : mega20221229@gmail.com
    password: hkxdtkapxhuyyxma
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      
server:
  port: 80
  
