spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_221229?characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  main:
    allow-circular-references: true    


server:
  port: 80